name: flutter_meets_igbo
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  easy_localization: ^3.0.7+1
  faker: ^2.2.0
  flutter:
    sdk: flutter
  flutter_widget_from_html: ^0.16.0
  intl: ^0.19.0
  lukehog: ^0.4.6
  persistent_bottom_nav_bar: ^6.2.1

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  generate: true

  assets:
    - assets/images/
    - assets/l10n/
    - assets/story/

# flutter_icons:
#   image_path: "assets/images/logo.png"
#   android: false
#   ios: true
#   remove_alpha_ios: true
# flutter_native_splash:
#   color: "#ffffff"
#   image: assets/images/logo.png
#   android: true
#   ios: true
#   web: false
#   fullscreen: true
#   android_gravity: center
